name: CI Express

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  ci-express:
    uses: ./.github/workflows/ci-shared.yml
    with:
      node-version: "20"
    secrets:
      STAGING_API_KEY: ${{ secrets.STAGING_API_KEY }}