name: CI Shared

on:
  workflow_call:
    inputs:
      node-version:
        description: "Version de Node.js à utiliser"
        required: true
        type: string
      working-directory:
        description: "Répertoire de travail"
        required: false
        type: string
        default: "."
    secrets:
      STAGING_API_KEY:
        required: false

jobs:
  ci:
    runs-on: ubuntu-latest
    environment: staging

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4

      - name: Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
        env:
          STAGING_API_KEY: ${{ secrets.STAGING_API_KEY }}