name: Deploy Render

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Render
        run: |
          curl -f -X POST \
            "https://api.render.com/v1/services/srv-d8gk1v1kh4rs73ap7d90/deploys" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{}'